steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/my-cloudbuild-image'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/my-cloudbuild-image'
#test ver2